### ISSUE TITLE
make run-singularity on fs5 on DAS5 gives "cwltool: error: unrecognized arguments: --singularity"

### ISSUE THREAD

**Issue by HannoSpreeuw** [EOSC-LOFAR/prefactor-cwl#27]
On fs5 on [DAS5](https://www.cs.vu.nl/das5/) (CentOS 7.4.1708)
make small 
module load singularity
make run-singularity
gives
.....
.....
cwltool: error: unrecognized arguments: --singularity
make: *** [run-singularity] Error 2

**Comment by HannoSpreeuw** [comment]
make slurm-singularity gives the same error.

**Comment by mr-c** [comment]
@HannoSpreeuw What is the output of `.virtualenv/bin/pip show cwltool` and `cwltool --version` ?

**Comment by HannoSpreeuw** [comment]
pip show cwltool
gives blank
Thanks!
After pip install cwltool
cwltool --version
gives 
/home/hspreeuw/anaconda3/bin/cwltool 1.0.20180923172926

**Comment by HannoSpreeuw** [comment]
But the error persists.
For run-singularity
cwltool: error: unrecognized arguments: --singularity
make: *** [run-singularity] Error 2

For make slurm-singularity
toil-cwl-runner: error: unrecognized arguments: --singularity

**Comment by mr-c** [comment]
@HannoSpreeuw Yes, because it uses the copy of `cwltool` or `toil-cwl-runner` inside the virtualenv.

I recommend deleting `.virtualenv` and pulling down the changes I just pushed: https://github.com/EOSC-LOFAR/prefactor-cwl/pull/28

**Comment by HannoSpreeuw** [comment]
So I did. Different error:
```
Successfully built dill scandir networkx googleapis-common-protos
Installing collected packages: six, webencodings, html5lib, atomicwrites, more-itertools, pluggy, attrs, scandir, pathlib2, py, funcsigs, pytest, urllib3, idna, chardet, certifi, requests, dill, subprocess32, future, psutil, coverage, pytest-cov, websocket-client, backports.ssl-match-hostname, ipaddress, docker-pycreds, docker, python-dateutil, ruamel.ordereddict, ruamel.yaml, avro, pyparsing, isodate, rdflib, rdflib-jsonld, typing, typing-extensions, lockfile, mistune, CacheControl, schema-salad, bagit, mypy-extensions, lxml, decorator, networkx, prov, shellescape, cwltool, docutils, pyyaml, galaxy-lib, protobuf, googleapis-common-protos, pytz, futures, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, apache-libcloud, retry-decorator, httplib2, oauth2client, enum34, pycparser, cffi, asn1crypto, cryptography, pyOpenSSL, boto, SocksiPy-branch, gcs-oauth2-boto-plugin, toil, pycrypto
Successfully installed CacheControl-0.11.7 SocksiPy-branch-1.1 apache-libcloud-2.2.1 asn1crypto-0.24.0 atomicwrites-1.2.1 attrs-18.2.0 avro-1.8.1 backports.ssl-match-hostname-3.5.0.1 bagit-1.7.0 boto-2.49.0 cachetools-2.1.0 certifi-2018.8.24 cffi-1.11.5 chardet-3.0.4 coverage-4.5.1 cryptography-2.3.1 cwltool-1.0.20180820141117 decorator-4.3.0 dill-0.2.7.1 docker-2.5.1 docker-pycreds-0.3.0 docutils-0.14 enum34-1.1.6 funcsigs-1.0.2 future-0.16.0 futures-3.2.0 galaxy-lib-17.9.3 gcs-oauth2-boto-plugin-1.14 google-api-core-0.1.4 google-auth-1.5.1 google-cloud-core-0.28.1 google-cloud-storage-1.6.0 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 html5lib-1.0.1 httplib2-0.11.3 idna-2.6 ipaddress-1.0.22 isodate-0.6.0 lockfile-0.12.2 lxml-4.2.5 mistune-0.7.4 more-itertools-4.3.0 mypy-extensions-0.4.1 networkx-2.2 oauth2client-4.1.3 pathlib2-2.3.2 pluggy-0.7.1 protobuf-3.6.1 prov-1.5.1 psutil-3.0.1 py-1.6.0 pyOpenSSL-18.0.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.19 pycrypto-2.6.1 pyparsing-2.2.2 pytest-3.7.4 pytest-cov-2.5.1 python-dateutil-2.7.3 pytz-2018.5 pyyaml-3.13 rdflib-4.2.2 rdflib-jsonld-0.4.0 requests-2.18.4 retry-decorator-1.1.0 rsa-4.0 ruamel.ordereddict-0.4.13 ruamel.yaml-0.15.51 scandir-1.9.0 schema-salad-2.7.20180905124720 shellescape-3.4.1 six-1.11.0 subprocess32-3.5.2 toil-3.18.0 typing-3.6.6 typing-extensions-3.6.6 urllib3-1.22 webencodings-0.5.1 websocket-client-0.53.0
mkdir -p /home/hspreeuw/prefactor-cwl/runs/run_2018-10-08-12-04-50
.virtualenv/bin/cwltool \
	--singularity \
	--leave-tmpdir \
	--cachedir cache \
	--outdir /home/hspreeuw/prefactor-cwl/runs/run_2018-10-08-12-04-50/results \
	prefactor.cwl \
	jobs/job_20sb.yaml > >(tee /home/hspreeuw/prefactor-cwl/runs/run_2018-10-08-12-04-50/output) 2> >(tee /home/hspreeuw/prefactor-cwl/runs/run_2018-10-08-12-04-50/log >&2)
.virtualenv/bin/cwltool 1.0.20180820141117
Resolved 'prefactor.cwl' to 'file:///home/hspreeuw/prefactor-cwl/prefactor.cwl'
/home/hspreeuw/prefactor-cwl/.virtualenv/lib/python2.7/site-packages/ruamel/yaml/constructor.py:266: DuplicateKeyFutureWarning: while constructing a mapping
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 1, column 1
found duplicate key "cwlVersion" with value "v1.0" (original value: "v1.0")
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 4, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
/home/hspreeuw/prefactor-cwl/.virtualenv/lib/python2.7/site-packages/ruamel/yaml/constructor.py:266: DuplicateKeyFutureWarning: while constructing a mapping
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 251, column 3
found duplicate key "s:person.url" with value "https://orcid.org/0000-0001-5125-9539" (original value: "http://orcid.org/0000-0002-6136-3724")
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 252, column 3

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Workflow checker warning:
prefactor.cwl:181:7: 'dclock_1st' is not an input parameter of
                     file:///home/hspreeuw/prefactor-cwl/steps/plots.cwl, expected amplitude_array,
                     dclock_1st_sm, dtec_1st_sm
[workflow ] start
[workflow ] starting step ndppp_prep_cal
[step ndppp_prep_cal] start
[job ndppp_prep_cal] Output of job will be cached in /home/hspreeuw/prefactor-cwl/cache/187eef3d15e77102e21a6feb47bb8d9f
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/kernsuite/prefactor:latest
Cache folder set to /home/hspreeuw/.singularity/docker
Importing: base Singularity environment
Importing: /home/hspreeuw/.singularity/docker/sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Importing: /home/hspreeuw/.singularity/docker/sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
Importing: /home/hspreeuw/.singularity/docker/sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
Importing: /home/hspreeuw/.singularity/docker/sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
Importing: /home/hspreeuw/.singularity/docker/sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
Importing: /home/hspreeuw/.singularity/docker/sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz

gzip: /home/hspreeuw/.singularity/docker/sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!
Workflow error, try again with --debug for more information:
Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Command '['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']' returned non-zero exit status 2.
make: *** [run-singularity] Error 1
```
but similar to #24

**Comment by mr-c** [comment]
@HannoSpreeuw Progress? :-)
What is your Singularity version?

```
singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor
```
works for me with
```
$ singularity --version
2.5.2-dist
```

**Comment by HannoSpreeuw** [comment]
[hspreeuw@fs5 prefactor-cwl]$ singularity --version
2.4-master.g718360b

**Comment by mr-c** [comment]
@HannoSpreeuw Feels like a Singularity issue to me. Can you try a new version?

**Comment by HannoSpreeuw** [comment]
This is the latest available singularity on fs5.
I'll ask fs5 maintenance for an update.

**Comment by HannoSpreeuw** [comment]
System management installed Singularity 3.0.0. The latest, allegedly.
rm -rf .virtualenv
make run-singularity
gives
"
....
....
Resolved 'prefactor.cwl' to 'file:///home/hspreeuw/prefactor-cwl/prefactor.cwl'
/home/hspreeuw/prefactor-cwl/.virtualenv/lib/python2.7/site-packages/ruamel/yaml/constructor.py:266: DuplicateKeyFutureWarning: while constructing a mapping
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 1, column 1
found duplicate key "cwlVersion" with value "v1.0" (original value: "v1.0")
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 4, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
/home/hspreeuw/prefactor-cwl/.virtualenv/lib/python2.7/site-packages/ruamel/yaml/constructor.py:266: DuplicateKeyFutureWarning: while constructing a mapping
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 251, column 3
found duplicate key "s:person.url" with value "https://orcid.org/0000-0001-5125-9539" (original value: "http://orcid.org/0000-0002-6136-3724")
  in "file:///home/hspreeuw/prefactor-cwl/prefactor.cwl", line 252, column 3

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Workflow checker warning:
prefactor.cwl:181:7: 'dclock_1st' is not an input parameter of
                     file:///home/hspreeuw/prefactor-cwl/steps/plots.cwl, expected amplitude_array,
                     dclock_1st_sm, dtec_1st_sm
[workflow ] start
[workflow ] starting step ndppp_prep_cal
[step ndppp_prep_cal] start
[job ndppp_prep_cal] Output of job will be cached in /home/hspreeuw/prefactor-cwl/cache/187eef3d15e77102e21a6feb47bb8d9f
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
Error: unknown flag: --name
Usage:
  singularity [global options...] pull [pull options...] <URI>

Workflow error, try again with --debug for more information:
Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Command '['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']' returned non-zero exit status 1.
make: *** [run-singularity] Error 1
"

**Comment by mr-c** [comment]
That was a quick upgrade! And 3.0.0 is very new, it came out two days ago. Looks like they broke some of the command line interface, and re-wrote their entire codebase (!!)

This will need a lot of testing by the `cwltool` developers (myself and others), so I'll get back to you.

In the meantime, the system administrators could downgrade to Singularity 2.6.0 which should work with `cwltool` and `toil-cwl-runnet` as is.

**Comment by mr-c** [comment]
I've reported the break in Singularity's command line interface at https://github.com/sylabs/singularity/issues/2214

**Comment by HannoSpreeuw** [comment]
System management also installed 2.5.2 for me:
[hspreeuw@fs5 prefactor-cwl]$ singularity --version
2.5.2-dist

make run-singularity
[workflow ] start
[workflow ] starting step ndppp_prep_cal
[step ndppp_prep_cal] start
[job ndppp_prep_cal] Output of job will be cached in /home/hspreeuw/prefactor-cwl/cache/187eef3d15e77102e21a6feb47bb8d9f
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/kernsuite/prefactor:latest
Cache folder set to /home/hspreeuw/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Exploding layer: sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
Exploding layer: sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
Exploding layer: sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
Exploding layer: sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
Exploding layer: sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz
ERROR  : Error applying layer whiteouts
ABORT  : Retval = 255
Cleaning up...
ERROR: pulling container failed!
Workflow error, try again with --debug for more information:
Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Command '['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']' returned non-zero exit status 255.
make: *** [run-singularity] Error 1

**Comment by gijzelaerr** [comment]
does running `$ singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor` work? (for 2.5.2)

**Comment by HannoSpreeuw** [comment]
[hspreeuw@fs5 prefactor-cwl]$ singularity --version
2.5.2-dist
[hspreeuw@fs5 prefactor-cwl]$ singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor 
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/kernsuite/prefactor:latest
Cache folder set to /home/hspreeuw/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Exploding layer: sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
Exploding layer: sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
Exploding layer: sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
Exploding layer: sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
Exploding layer: sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz
ERROR  : Error applying layer whiteouts
ABORT  : Retval = 255
Cleaning up...
ERROR: pulling container failed!

**Comment by mr-c** [comment]
hmm.. works for me using the Debian packaged version of Singularity: https://packages.debian.org/buster/singularity-container

Maybe they included patches that were part of the Singularity 2.6 release? https://github.com/sylabs/singularity/releases/tag/2.6.0

**Comment by HannoSpreeuw** [comment]
Thanks for all your good help, but I am giving up attempts on this cluster. Will try my own laptop (Manjaro = Arch) and if that does not work an Ubuntu 18.04 VM.

**Comment by gijzelaerr** [comment]
> [hspreeuw@fs5 prefactor-cwl]$ singularity --version
> 2.5.2-dist
> [hspreeuw@fs5 prefactor-cwl]$ singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor
> WARNING: pull for Docker Hub is not guaranteed to produce the
> WARNING: same image on repeated pull. Use Singularity Registry
> WARNING: (shub://) to pull exactly equivalent images.
> Docker image path: index.docker.io/kernsuite/prefactor:latest
> Cache folder set to /home/hspreeuw/.singularity/docker
> Importing: base Singularity environment
> Exploding layer: sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
> Exploding layer: sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
> Exploding layer: sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
> Exploding layer: sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
> Exploding layer: sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
> Exploding layer: sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz
> ERROR : Error applying layer whiteouts
> ABORT : Retval = 255
> Cleaning up...
> ERROR: pulling container failed!

there seems to be something wrong with that singularity configuration/installation on that node or cluster.

**Comment by HannoSpreeuw** [comment]
Okay. Let me contact system maintenance.

**Comment by HannoSpreeuw** [comment]
Problem solved by fs5 maintenance: disk quota problem on my account.

**Comment by HannoSpreeuw** [comment]
Problem solved by fs5 maintenance: disk quota problem on my account.

**Comment by gijzelaerr** [comment]
zal ik m dan ook nog ff openen en sluiten

**Comment by HannoSpreeuw** [comment]
Sorry, I was confused.
After I was allocated additional disk quota, 
I could run `make run-udocker` up to #23 
I also could run e.g.
`singularity pull docker://flatironinstitute/triqs:unstable`
with singularity 2.5.2-dist
However 
`make run-singularity`
still gives

> [job calib_cal_20] Using cached output in /home/hspreeuw/prefactor-cwl/cache/06aded945abf766882d0daeaf876b148
[step calib_cal] completed success
[workflow ] starting step do_magic
[step do_magic] start
[job do_magic] Output of job will be cached in /home/hspreeuw/prefactor-cwl/cache/beb5265705eeddf4aed154aa5c85cfb8
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/kernsuite/prefactor:latest
Cache folder set to /home/hspreeuw/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913.tar.gz
Exploding layer: sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6.tar.gz
Exploding layer: sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67.tar.gz
Exploding layer: sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418.tar.gz
Exploding layer: sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2.tar.gz
Exploding layer: sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c.tar.gz
ERROR  : Error applying layer whiteouts
ABORT  : Retval = 255
Cleaning up...
ERROR: pulling container failed!
Workflow error, try again with --debug for more information:
Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Command '['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']' returned non-zero exit status 255.
make: *** [run-singularity] Error 1

**Comment by mr-c** [comment]
@HannoSpreeuw Can you work with your colleagues to get `singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor` working? Once that works, then `toil-cwl-runner` & `cwltool` will work.

One piece of information that would be helpful, what filesystem is `/home/hspreeuw/prefactor-cwl/cache` ?
`stat -f -c %T  /home/hspreeuw/` should have the answer

**Comment by HannoSpreeuw** [comment]
Okay.

xfs

**Comment by mr-c** [comment]
@HannoSpreeuw Thanks. I don't see any know issues with XFS & Singularity (there are some with BeeGFS)

My advice remains to work with your colleagues to get `singularity pull docker://kernsuite/prefactor working`? Once that works, then toil-cwl-runner & cwltool will work.

**Comment by HannoSpreeuw** [comment]
This works for singularity 3.0.0, but not for 2.5.2-dist:
[hspreeuw@fs5 ~]$ module load singularity/3.0.0
[hspreeuw@fs5 ~]$ singularity pull docker://kernsuite/prefactor
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913
 45.41 MiB / 45.41 MiB [====================================================] 0s
Copying blob sha256:c59d01a7e4caf1aba785eb33192fec3f96e4ab01975962bcec10f4989a6edcc6
 848 B / 848 B [============================================================] 0s
Copying blob sha256:41ba73a9054d231e1f555c40a74762276900cc6487f5c6cf13b89c7606635c67
 619 B / 619 B [============================================================] 0s
Copying blob sha256:f1bbfd495cc1112b503350686641ee4fa2cea8ccd13fb8a8a302c81dae61d418
 854 B / 854 B [============================================================] 0s
Copying blob sha256:0c346f7223e24b517358f52c4a3f5f9af1c86e5ddeaee5659c8889846e46d1e2
 169 B / 169 B [============================================================] 0s
Copying blob sha256:760bbf8251916f26631b53355347bcfdc0274d9b455b2ad9017ddc87b5c5a83c
 288 B / 288 B [============================================================] 0s
Copying blob sha256:d92598cf94b04c7b388143c4ec91a867e415c299d97970f90cbbe0c586afd661
 46.24 MiB / 46.24 MiB [====================================================] 0s
Copying blob sha256:44bd5d573b1bf3b0c10cd3f4622fb8682abf34e828fddb042bc897b563a3460a
 7.58 KiB / 7.58 KiB [======================================================] 0s
Copying blob sha256:92c8ae71df9ef968b3f02aa60be0b4b957371120b748b1f54e7fcf5ac769b66e
 89 B / 89 B [==============================================================] 0s
Copying blob sha256:7c66b3b256d7e54d498dee22b146ce288bac00877272b59ea4c6e1f21c7f1988
 92 B / 92 B [==============================================================] 0s
Copying blob sha256:a22c18e00204f5f149a7328b37c3473d69019471f0a25daae6925e7f96602b77
 295.43 MiB / 295.43 MiB [==================================================] 4s
Copying blob sha256:a3a761fd9e05053e844a5b226f290d40e814fe6bccf5bb5428cd4ac2dddfc62b
 7.03 MiB / 7.03 MiB [======================================================] 0s
Copying config sha256:ae80dffaf8b3e40ebf9878340dc0e88ecb483a44db5ea02fd863a9e41a60cb5b
 4.50 KiB / 4.50 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: prefactor_latest.sif

**Comment by mr-c** [comment]
@HannoSpreeuw Interesting! I'll see if I can add Singularity 3.0.0 support soon.

**Comment by mr-c** [comment]
@HannoSpreeuw While we wait for that, you can make the following local modification to see if it is good enough.

```
echo $(pip show cwltool | grep Location | awk '{print $2}')/cwltool/singularity.py
```
And edit the path it produces. Look for and make the following change:
``` diff
diff --git a/cwltool/singularity.py b/cwltool/singularity.py
index cd1bb9e0..2633e8b9 100644
--- a/cwltool/singularity.py
+++ b/cwltool/singularity.py
@@ -98,7 +98,7 @@ class SingularityCommandLineJob(ContainerCommandLineJob):
         if (force_pull or not found) and pull_image:
             cmd = []  # type: List[Text]
             if "dockerPull" in dockerRequirement:
-                cmd = ["singularity", "pull", "--force", "--name",
+                cmd = ["singularity", "pull", "--force", 
                        str(dockerRequirement["dockerImageId"]),
                        str(dockerRequirement["dockerPull"])]
                 _logger.info(Text(cmd))
```

**Comment by HannoSpreeuw** [comment]
[hspreeuw@fs5 prefactor-cwl]$ echo $(pip show cwltool | grep Location | awk '{print $2}')/cwltool/singularity.py
/cwltool/singularity.py
[hspreeuw@fs5 prefactor-cwl]$ ls /cwltool/singularity.py
ls: cannot access /cwltool/singularity.py: No such file or directory

**Comment by HannoSpreeuw** [comment]
[hspreeuw@fs5 prefactor-cwl]$ find . -name singularity.py
./.virtualenv/lib/python2.7/site-packages/cwltool/singularity.py

Got it.

**Comment by mr-c** [comment]
> [hspreeuw@fs5 prefactor-cwl]$ echo $(pip show cwltool | grep Location | awk '{print $2}')/cwltool/singularity.py
/cwltool/singularity.py
[hspreeuw@fs5 prefactor-cwl]$ ls /cwltool/singularity.py
ls: cannot access /cwltool/singularity.py: No such file or directory

oh yeah, you have to activate the virtualenv or call it directly:

```
echo $(.virtualenv/bin/pip show cwltool | grep Location | awk '{print $2}')/cwltool/singularity.py
```

**Comment by HannoSpreeuw** [comment]
Success!
Now running into #23
