### ISSUE TITLE
File format not recognized.

### ISSUE THREAD

**Issue by DailyDreaming** [EOSC-LOFAR/prefactor-cwl#7]
Hi, I just attempted to run this and got the following error upon `make run`:

`lifeisaboutfishtacos@TacoTruck:~/Desktop/LOFAR/prefactor-cwl$ make run`
`cd data && tar Jxvf L570745_uv_first10.MS.tar.xz`
`xz: (stdin): File format not recognized`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now`
`Makefile:19: recipe for target 'data/L570745_SB000_uv_first10.MS/' failed`
`make: *** [data/L570745_SB000_uv_first10.MS/] Error 2`

**Comment by mr-c** [comment]
Hello, do you have git-lfs installed?

**Comment by DailyDreaming** [comment]
I do.

**Comment by DailyDreaming** [comment]
Sorry I missed it the first time.  The error seems to be:

`Downloading data/L570745_uv_first10.MS.tar.xz (387 MB)`
`Error downloading object: data/L570745_uv_first10.MS.tar.xz (d6acef4): Smudge error: Error downloading data/L570745_uv_first10.MS.tar.xz`
`(d6acef40bcf795c5ae94232654414fece4a20eb75494577ea630fc663673b3c1): batch response: This repository is over its data quota.`
`Purchase more data packs to restore access.`

**Comment by gijzelaerr** [comment]
this is fixed now, i modified the Makefile script to retrieve the data from a FTP server. Let me know if there is a problem.
