### ISSUE TITLE
Missing npy tables in prefactor.cwl outputs

### ISSUE THREAD

**Issue by manuorru** [EOSC-LOFAR/prefactor-cwl#8]
Hi Gijs, 

I have noticed that in the outputs section of the prefactor.cwl I think I miss the npy files which are the calibration tables and that are the real output of this pipeline. 

In case it could be useful, please find below the list of results you would expect from pre-factor:
amp_allsols.png
caldata_transfer_amplitude_array.npy
caldata_transfer_amplitude_array.txt
caldata_transfer_phase_array.npy
caldata_transfer_station_names.npy
cal_phases_polXX_dirpointing.png
cal_phases_polYY_dirpointing.png
dclock_allsols.png
dtec_allsols.png
fitted_data_dclock_caldata_transfer_1st.npy
fitted_data_dclock_caldata_transfer_1st.sm.npy
fitted_data_dTEC_caldata_transfer_1st.npy
fitted_data_dTEC_caldata_transfer_1st.sm.npy
freqs_for_amplitude_array.npy
freqs_for_phase_array.npy
h5imp_cal_losoto.h5
matrix_xx.png
matrix_yy.png
phase_xx_yy_offset.png

Thanks for looking into it. 
Cheers, 
Manu

**Comment by gijzelaerr** [comment]
I think that should solve the problem. Let me know if you are still missing a file.
